FROM nginx:stable-alpine

# Create the /var/www/html directory
RUN mkdir -p /var/www/html

# Set permissions for /var/www/html
# RUN chown -R www-data:www-data /var/www/html

# Continue with your other configurations...
