version: '3.8'
services:
  app:
    build:
      args:
        user: nguyenhau
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    # restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    networks:
      - course_be_network

  nginx:
    image: nginx:stable-alpine
    # restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - course_be_network

  db:
    image: postgres
    # restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: course
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ~/test/:/var/lib/postgresql/data
    networks:
      - course_be_network

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    networks:
      - course_be_network

# Docker Networks
networks:
  course_be_network:
    driver: bridge
volumes:
  postgres_data: