name: Docker Compose

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: isbang/compose-action@v1.5.1
            

      

      - name: Build and push Docker images
        run: |
          docker-compose build
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker-compose push

      - name: SSH into Digital Ocean server and pull images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /path/to/your/laravel/app
            docker-compose pull

      - name: Run Docker Compose on Digital Ocean server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /path/to/your/laravel/app
            docker-compose up -d
